console.log("Hey Abu Hurairah, I have started learning TypeScript.");
var Name:string = "Anum";
console.log (Name);
var num1:number = 10;
var num2:number = 20;
var num3:number = 30;
var num4:number = 40;
var num5:number = 50;
var num6:number = 60;
var num7:number = 70;
var num8:number = 80;
var num9:number = 90;
var num10:number = 100;
var addition :number = (num1+num2+num3+num4+num5+num6+num7+num8+num9+num10);
var subtraction :number = (num1-num2-num3-num4-num5-num6-num7-num8-num9-num10);
var multiply:number = (num1*num2*num3*num4*num5*num6*num7*num8*num9*num10);
var division :number = (num10/num2);
console.log(addition);
console.log(subtraction);
console.log(multiply);
console.log(division);